import { defineRouteMiddleware } from "@astrojs/starlight/route-data";

type SidebarEntry = App.Locals["starlightRoute"]["sidebar"][number];

/**
 * An autogenerated sidebar group for a subdirectory is labelled with the bare
 * directory name. These are the labels to show instead.
 */
const DIRECTORY_LABELS: Record<string, string> = { tools: "Tools" };

function relabel(entries: SidebarEntry[]): void {
  for (const entry of entries) {
    if (entry.type !== "group") continue;
    entry.label = DIRECTORY_LABELS[entry.label] ?? entry.label;
    relabel(entry.entries);
  }
}

export const onRequest = defineRouteMiddleware((context) => {
  // Top-level groups are labelled in astro.config.mjs; only nested ones need it.
  for (const entry of context.locals.starlightRoute.sidebar) {
    if (entry.type === "group") relabel(entry.entries);
  }
});
